version: "3"

services:
  web:
    build: ./docker/python/Dockerfile.prod
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
        - .:/usr/src/app

  elastic_search:
    image: elasticsearch:latest
    container_name: elastic_search
    ports:
      - "9200:9200"
    networks:
      - docker_elk

  kibana:
    image: kibana:latest
    container_name: kibana
    depends_on:
      - elastic_search
    ports:
      - "5601:5601"
    networks:
      - docker_elk
